
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

# Text to speech
tts:
  - platform: google_translate

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml


##############################################################
template:
 - binary_sensor: !include_dir_merge_list template_binary_sensors
 - sensor: !include_dir_merge_list template_sensors

 
#############################################################          #Prevition nextion jour
 - trigger:
      - platform: time_pattern
        hours: /1
      - platform: homeassistant
        event: start
   action:
      - service: weather.get_forecasts
        data:
          #type: hourly
          type: daily
        target:
          entity_id: weather.saint_vincent_de_tyrosse
        response_variable: daily_var
   sensor:
      - name: Prevision_Meteo_Nextion_J
        unique_id: nextion_weather_forcast_daily
        state: "{{ daily_var['weather.saint_vincent_de_tyrosse'].forecast[0].condition }}"
        attributes:
          forecast: "{{ daily_var['weather.saint_vincent_de_tyrosse'].forecast }}"
#############################################################          #Prevition nextion heure
 - trigger:
      - platform: time_pattern
        hours: /1
      - platform: homeassistant
        event: start
   action:
      - service: weather.get_forecasts
        data:
          type: hourly
          #type: daily
        target:
          entity_id: weather.saint_vincent_de_tyrosse
        response_variable: hourly_var
   sensor:
      - name: Prevision_Meteo_Nextion_H
        unique_id: nextion_weather_forcast_hourly
        state: "{{ hourly_var['weather.saint_vincent_de_tyrosse'].forecast[0].condition }}"
        attributes:
          forecast: "{{ hourly_var['weather.saint_vincent_de_tyrosse'].forecast }}"

# --------------- Partie sensor----------------------------------------------------------------     (states['sensor.saint_vincent_de_tyrosse_next_rain'].attributes['1_hour_forecast']['0 min'] == 'Pluie modérée')
sensor:

 - platform: time_date
   display_options:
     - 'time'
     - 'date'
