esphome:
  name: meteo35

esp32:
  board: az-delivery-devkit-v4
  framework:
    type: arduino

# Enable logging
logger:
  baud_rate: 0     # Disable UART logging (pins GPIO1/3 are used for Nextion communication)
  level: VERY_VERBOSE

# Enable Home Assistant API
api:

ota:
  password: "613c4870f0101981a29542c6f7738f42"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password


uart:
  tx_pin: GPIO1
  rx_pin: GPIO3
  baud_rate: 115200
  rx_buffer_size: 1024
  
time:
  - platform: sntp
    id: sntp_time
    timezone: Europe/Paris
globals:
 - id: display_on
   type: bool
#---------- Envois des données récupéré sur les différentes zones de l'ecran---------------
display:
  - platform: nextion
    id: teplomer
    update_interval: 4s
    lambda: |-
                auto time = id(sntp_time).now();
                it.set_component_text_printf("heure","%02d",time.hour);
                it.set_component_text_printf("minute","%02d",time.minute);
                it.set_component_text_printf("date",id(date_simple).state.c_str());
                it.send_command_printf("%s.pic=%.0f", "icon",id(today_icon).state);
                it.send_command_printf("%s.pic=%.0f", "icon_jour",id(today_jour).state);
                it.send_command_printf("%s.pic=%.0f", "icon_dem",id(today_icon1).state);
                it.send_command_printf("%s.pic=%.0f", "Icon_2j",id(today_icon2).state);
                it.send_command_printf("%s.pic=%.0f", "Icon_3j",id(today_icon3).state);
                it.set_component_text_printf("T_min_jour","%.0f",id(jour_tmin).state);
                it.set_component_text_printf("T_max_jour","%.0f",id(jour_tmax).state);
                it.set_component_text_printf("T_min_dem","%.0f",id(dem_tmin).state);
                it.set_component_text_printf("T_max_dem","%.0f",id(dem_tmax).state);
                it.set_component_text_printf("T_min_j2","%.0f",id(j2_tmin).state);
                it.set_component_text_printf("T_max_j2","%.0f",id(j2_tmax).state);
                it.set_component_text_printf("T_min_j3","%.0f",id(j3_tmin).state);
                it.set_component_text_printf("T_max_j3","%.0f",id(j3_tmax).state);
                it.set_component_value("temp_1",id(sonde_ext_temp).state);
                it.set_component_value("hum_1",id(sonde_humi_ext).state);
                it.send_command_printf("%s.picc=%.0f","gel",id(alerte_gel).state);
                it.send_command_printf("%s.picc=%.0f","neige",id(alerte_neige).state);
                it.set_component_value("alert_coul",id(alerte_coul).state);
                it.send_command_printf("%s.picc=%.0f","alerte_rain",id(alerte_rain).state);
                it.send_command_printf("%s.pic=%.0f", "mn_0",id(pluie_0mn).state);
                it.send_command_printf("%s.pic=%.0f", "mn_5",id(pluie_5mn).state);
                it.send_command_printf("%s.pic=%.0f", "mn_10",id(pluie_10mn).state);
                it.send_command_printf("%s.pic=%.0f", "mn_15",id(pluie_15mn).state);
                it.send_command_printf("%s.pic=%.0f", "mn_20",id(pluie_20mn).state);
                it.send_command_printf("%s.pic=%.0f", "mn_25",id(pluie_25mn).state);
                it.send_command_printf("%s.pic=%.0f", "mn_30",id(pluie_30mn).state);
                it.send_command_printf("%s.pic=%.0f", "mn_35",id(pluie_35mn).state);
                it.send_command_printf("%s.pic=%.0f", "mn_40",id(pluie_40mn).state);
                it.send_command_printf("%s.pic=%.0f", "mn_45",id(pluie_45mn).state);
                it.send_command_printf("%s.pic=%.0f", "mn_50",id(pluie_50mn).state);
                it.send_command_printf("%s.pic=%.0f", "mn_55",id(pluie_55mn).state);
                it.send_command_printf("%s.pic=%.0f", "alert_vent",id(alert_vent).state);
                it.send_command_printf("%s.pic=%.0f", "alert_inondat",id(alert_inondation).state);
                it.send_command_printf("%s.pic=%.0f", "alert_orages",id(alert_orages).state);
                it.send_command_printf("%s.pic=%.0f", "alert_pluie_in",id(alert_pluie_inondation).state);
                it.send_command_printf("%s.pic=%.0f", "alert_neig_ver",id(alert_neige_verglas).state);
                it.send_command_printf("%s.pic=%.0f", "alert_froid",id(alert_grand_froid).state);
                it.send_command_printf("%s.pic=%.0f", "alert_vagues",id(alert_vagues_submersion).state);

#----- Récupération des données à afficher-----------------------
#-------------------------- sensor -----
sensor:

  - platform: homeassistant
    id: alert_vent 
    entity_id: sensor.alert_vent 
  - platform: homeassistant
    id: alert_inondation 
    entity_id: sensor.alert_inondation 
  - platform: homeassistant
    id: alert_orages 
    entity_id: sensor.alert_orages 
  - platform: homeassistant
    id: alert_pluie_inondation 
    entity_id: sensor.alert_pluie_inondation 
  - platform: homeassistant
    id: alert_neige_verglas 
    entity_id: sensor.alert_neige_verglas 
  - platform: homeassistant
    id: alert_grand_froid 
    entity_id: sensor.alert_grand_froid 
  - platform: homeassistant
    id: alert_vagues_submersion 
    entity_id: sensor.alert_vagues_submersion 
#--------Pour les alertes neige et gel----------------------------------
  - platform: homeassistant
    id: alerte_gel
    entity_id: sensor.alerte_gel
  - platform: homeassistant
    id: alerte_neige
    entity_id: sensor.alerte_neige
  - platform: homeassistant
    id: alerte_rain
    entity_id: sensor.alerte_rain
#--------Pour les averses sur 1h00----------------------------------
  - platform: homeassistant
    id: pluie_0mn 
    entity_id: sensor.pluie_0mn 
  - platform: homeassistant
    id: pluie_5mn
    entity_id: sensor.pluie_5mn
  - platform: homeassistant
    id: pluie_10mn 
    entity_id: sensor.pluie_10mn 
  - platform: homeassistant
    id: pluie_15mn
    entity_id: sensor.pluie_15mn
  - platform: homeassistant
    id: pluie_20mn 
    entity_id: sensor.pluie_20mn 
  - platform: homeassistant
    id: pluie_25mn
    entity_id: sensor.pluie_25mn
  - platform: homeassistant
    id: pluie_30mn 
    entity_id: sensor.pluie_30mn 
  - platform: homeassistant
    id: pluie_35mn
    entity_id: sensor.pluie_35mn
  - platform: homeassistant
    id: pluie_40mn 
    entity_id: sensor.pluie_40mn 
  - platform: homeassistant
    id: pluie_45mn
    entity_id: sensor.pluie_45mn
  - platform: homeassistant
    id: pluie_50mn 
    entity_id: sensor.pluie_50mn 
  - platform: homeassistant
    id: pluie_55mn
    entity_id: sensor.pluie_55mn
#------------------------Pour les icones des prévisions préparé dans le configuration.yaml, pour le choix du numero des images à afficher en f() du temps
  - platform: homeassistant
    id: today_icon
    entity_id: sensor.today_icon
  - platform: homeassistant
    id: today_jour
    entity_id: sensor.jour
  - platform: homeassistant
    id: today_icon1
    entity_id: sensor.today_icon1
  - platform: homeassistant
    id: today_icon2
    entity_id: sensor.today_icon2
  - platform: homeassistant
    id: today_icon3
    entity_id: sensor.today_icon3
  - platform: homeassistant
    id: jour_tmax
#--------Pour les minima maxima des temperatures prevus
    entity_id: sensor.jour_tmax
  - platform: homeassistant
    id: jour_tmin
    entity_id: sensor.jour_tmin
  - platform: homeassistant
    id: dem_tmax
    entity_id: sensor.dem_tmax
  - platform: homeassistant
    id: dem_tmin
    entity_id: sensor.dem_tmin
  - platform: homeassistant
    id: j2_tmax
    entity_id: sensor.j2_tmax
  - platform: homeassistant
    id: j2_tmin
    entity_id: sensor.j2_tmin
  - platform: homeassistant
    id: j3_tmax
    entity_id: sensor.j3_tmax
  - platform: homeassistant
    id: j3_tmin
    entity_id: sensor.j3_tmin
#------Pour les capteurs de sondes météo, à remplacer par vos sondes
  - platform: homeassistant
    id: sonde_ext_temp
    entity_id: sensor.temp_ext
  - platform: homeassistant
    id: text_alert
    entity_id: sensor.text_alert
  - platform: homeassistant
    id: sonde_humi_ext
    entity_id: sensor.humi_ext
#---------Définition de la couleur de l'alerte météo
  - platform: homeassistant
    id: alerte_coul
    entity_id:  sensor.alerte_coul
#-------------------------- text_sensor ------------------------------------------------------------------------------------------
#-----Pour la date
text_sensor:
  - platform: homeassistant
    id: date_simple
    entity_id: sensor.date_simple
#---------Retour d'informations pour le statut des interrupteurs, stocker dans des variable global à definir plus haut