esphome:
  name: meteo35

esp32:
  board: az-delivery-devkit-v4
  framework:
    type: arduino

# Enable logging
logger:
  baud_rate: 0     # Disable UART logging (pins GPIO1/3 are used for Nextion communication)
  level: VERY_VERBOSE

# Enable Home Assistant API
api:
  services:
    - service: update_tft
      then:
        - lambda: 'id(teplomer)->upload_tft();'

ota:
  password: "613c4870f0101981a29542c6f7738f42"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true

uart:
  tx_pin: GPIO1
  rx_pin: GPIO3
  baud_rate: 115200
  rx_buffer_size: 2048
  
time:
  - platform: sntp
    id: sntp_time
    timezone: Europe/Paris
globals:
 - id: display_on
   type: bool
 - id: current_brightness             # Is display on?
   type: float
   restore_value: no
   initial_value: '-1.0'
 - id: disp_page
   type: int
   restore_value: no
   initial_value: '0'
 - id: page
   type: int
   restore_value: no
   initial_value: '0'
#----- Récupération des données à afficher-----------------------
#-------------------------- sensor -----

binary_sensor:




  # 0. page - Overview
  - platform: nextion
    page_id: 0
    component_id: 9
    id: page1
    on_press:
      then:
        - lambda: 'id(page)=3;'
        - component.update: teplomer

        
  # 1. page - Lights
  - platform: nextion
    page_id: 0
    component_id: 27
    id: page2
    on_press:
      then:
        - lambda: 'id(page)=2;'
        - component.update: teplomer
        
  # 2. page - Media
  - platform: nextion
    page_id: 2
    component_id: 2
    id: page3
    on_press:
      then:
        - lambda: 'id(page)=3;'
        - component.update: teplomer
        
  # 3. page - Vacuum Cleaner  #Nothing to update here
  - platform: nextion
    page_id: 2
    component_id: 48
    id: page4
    on_press:
      then:
        - lambda: 'id(page)=1;'
        - component.update: teplomer

  # 4. page - Media
  - platform: nextion
    page_id: 3
    component_id: 2
    id: page5
    on_press:
      then:
        - lambda: 'id(page)=0;'
        - component.update: teplomer
        
  # 5. page - Vacuum Cleaner  #Nothing to update here
  - platform: nextion
    page_id: 3
    component_id: 40
    id: page6
    on_press:
      then:
        - lambda: 'id(page)=2;'
        - component.update: teplomer





sensor:

  - platform: nextion
    nextion_id: teplomer
    name: "n0"
    component_name: n0

  - platform: nextion
    id: disppage
    variable_name: dp
    update_interval: 1s

  - platform: homeassistant
    id: heure_icon_1
    entity_id: sensor.heure_icon_1
  - platform: homeassistant
    id: heure_t_1
    entity_id: sensor.heure_temp_1

  - platform: homeassistant
    id: heure_icon_2
    entity_id: sensor.heure_icon_2
  - platform: homeassistant
    id: heure_t_2
    entity_id: sensor.heure_temp_2

  - platform: homeassistant
    id: heure_icon_3
    entity_id: sensor.heure_icon_3
  - platform: homeassistant
    id: heure_t_3
    entity_id: sensor.heure_temp_3

  - platform: homeassistant
    id: heure_icon_4
    entity_id: sensor.heure_icon_4
  - platform: homeassistant
    id: heure_t_4
    entity_id: sensor.heure_temp_4

  - platform: homeassistant
    id: heure_icon_5
    entity_id: sensor.heure_icon_5
  - platform: homeassistant
    id: heure_t_5
    entity_id: sensor.heure_temp_5

  - platform: homeassistant
    id: heure_icon_6
    entity_id: sensor.heure_icon_6
  - platform: homeassistant
    id: heure_t_6
    entity_id: sensor.heure_temp_6

  - platform: homeassistant
    id: heure_icon_7
    entity_id: sensor.heure_icon_7
  - platform: homeassistant
    id: heure_t_7
    entity_id: sensor.heure_temp_7

  - platform: homeassistant
    id: heure_icon_8
    entity_id: sensor.heure_icon_8
  - platform: homeassistant
    id: heure_t_8
    entity_id: sensor.heure_temp_8


  - platform: homeassistant
    id: pluie_proch
    entity_id: sensor.pluie_proch

  - platform: homeassistant
    id: uv_prob 
    entity_id: sensor.uv_prob
  - platform: homeassistant
    id: alert_vent 
    entity_id: sensor.alert_vent
  - platform: homeassistant
    id: alert_inondation
    entity_id: sensor.alert_inondation
  - platform: homeassistant
    id: alert_orages 
    entity_id: sensor.alert_orages
  - platform: homeassistant
    id: alert_pluie_inondation
    entity_id: sensor.alert_pluie_inondation
  - platform: homeassistant
    id: alert_neige_verglas
    entity_id: sensor.alert_neige_verglas
  - platform: homeassistant
    id: alert_grand_froid
    entity_id: sensor.alert_grand_froid
  - platform: homeassistant
    id: alert_vagues_submersion
    entity_id: sensor.alert_vagues_submersion
#--------Pour les alertes neige et gel----------------------------------
  - platform: homeassistant
    id: alerte_gel
    entity_id: sensor.alerte_gel
  - platform: homeassistant
    id: alerte_neige
    entity_id: sensor.alerte_neige
  - platform: homeassistant
    id: alerte_rain
    entity_id: sensor.alerte_rain
#--------Pour les averses sur 1h00----------------------------------
  - platform: homeassistant
    id: pluie_0mn 
    entity_id: sensor.pluie_0mn 
  - platform: homeassistant
    id: pluie_5mn
    entity_id: sensor.pluie_5mn
  - platform: homeassistant
    id: pluie_10mn 
    entity_id: sensor.pluie_10mn 
  - platform: homeassistant
    id: pluie_15mn
    entity_id: sensor.pluie_15mn
  - platform: homeassistant
    id: pluie_20mn 
    entity_id: sensor.pluie_20mn 
  - platform: homeassistant
    id: pluie_25mn
    entity_id: sensor.pluie_25mn
  - platform: homeassistant
    id: pluie_30mn 
    entity_id: sensor.pluie_30mn 
  - platform: homeassistant
    id: pluie_35mn
    entity_id: sensor.pluie_35mn
  - platform: homeassistant
    id: pluie_40mn 
    entity_id: sensor.pluie_40mn 
  - platform: homeassistant
    id: pluie_45mn
    entity_id: sensor.pluie_45mn
  - platform: homeassistant
    id: pluie_50mn 
    entity_id: sensor.pluie_50mn 
  - platform: homeassistant
    id: pluie_55mn
    entity_id: sensor.pluie_55mn
#------------------------Pour les icones des prévisions préparé dans le configuration.yaml, pour le choix du numero des images à afficher en f() du temps
  - platform: homeassistant
    id: icon_meteo
    entity_id: sensor.icon_meteo
    on_value:
       then:
         - lambda: 'id(teplomer).send_command_printf("%s.pic=%.0f", "icon",id(icon_meteo).state);'

  - platform: homeassistant
    id: icon_jour_0
    entity_id: sensor.icon_jour_0
  - platform: homeassistant
    id: jour_tmax
    entity_id: sensor.jour_tmax
  - platform: homeassistant
    id: jour_tmin
    entity_id: sensor.jour_tmin

  - platform: homeassistant
    id: icon_jour_1
    entity_id: sensor.icon_jour_1
  - platform: homeassistant
    id: dem_tmax
    entity_id: sensor.dem_tmax
  - platform: homeassistant
    id: dem_tmin
    entity_id: sensor.dem_tmin

  - platform: homeassistant
    id: icon_jour_2
    entity_id: sensor.icon_jour_2
  - platform: homeassistant
    id: j2_tmax
    entity_id: sensor.j2_tmax
  - platform: homeassistant
    id: j2_tmin
    entity_id: sensor.j2_tmin

  - platform: homeassistant
    id: icon_jour_3
    entity_id: sensor.icon_jour_3
  - platform: homeassistant
    id: j3_tmax
    entity_id: sensor.j3_tmax
  - platform: homeassistant
    id: j3_tmin
    entity_id: sensor.j3_tmin

#------------------------Page 2
  - platform: homeassistant
    id: icon_jour_4
    entity_id: sensor.icon_jour_4
  - platform: homeassistant
    id: j4_tmax
    entity_id: sensor.j4_tmax
  - platform: homeassistant
    id: j4_tmin
    entity_id: sensor.j4_tmin
  - platform: homeassistant
    id: j4_pluis
    entity_id: sensor.j4_pluis

  - platform: homeassistant
    id: icon_jour_5
    entity_id: sensor.icon_jour_5
  - platform: homeassistant
    id: j5_tmax
    entity_id: sensor.j5_tmax
  - platform: homeassistant
    id: j5_tmin
    entity_id: sensor.j5_tmin
  - platform: homeassistant
    id: j5_pluis
    entity_id: sensor.j5_pluis

  - platform: homeassistant
    id: icon_jour_6
    entity_id: sensor.icon_jour_6
  - platform: homeassistant
    id: j6_tmax
    entity_id: sensor.j6_tmax
  - platform: homeassistant
    id: j6_tmin
    entity_id: sensor.j6_tmin
  - platform: homeassistant
    id: j6_pluis
    entity_id: sensor.j6_pluis

  - platform: homeassistant
    id: icon_jour_7
    entity_id: sensor.icon_jour_7
  - platform: homeassistant
    id: j7_tmax
    entity_id: sensor.j7_tmax
  - platform: homeassistant
    id: j7_tmin
    entity_id: sensor.j7_tmin
  - platform: homeassistant
    id: j7_pluis
    entity_id: sensor.j7_pluis

  - platform: homeassistant
    id: icon_jour_8
    entity_id: sensor.icon_jour_8
  - platform: homeassistant
    id: j8_tmax
    entity_id: sensor.j8_tmax
  - platform: homeassistant
    id: j8_tmin
    entity_id: sensor.j8_tmin
  - platform: homeassistant
    id: j8_pluis
    entity_id: sensor.j8_pluis

#------Pour les capteurs de sondes météo, à remplacer par vos sondes
  - platform: homeassistant
    id: sonde_ext_temp
    entity_id: sensor.temp_ext
  - platform: homeassistant
    id: text_alert
    entity_id: sensor.text_alert
  - platform: homeassistant
    id: sonde_humi_ext
    entity_id: sensor.humi_ext
#---------Définition de la couleur de l'alerte météo
  - platform: homeassistant
    id: alerte_coul
    entity_id:  sensor.alerte_coul
#-------------------------- text_sensor ------------------------------------------------------------------------------------------
#-----Pour la date
text_sensor:

  - platform: homeassistant
    id: date_simple
    entity_id: sensor.date_simple
    on_value:
       then:
         - component.update: teplomer

            
switch:
  - platform: restart
    name: Reboot Nextion3.5
    id: reboot


#
#
#
#
#---------- Envois des données récupéré sur les différentes zones de l'ecran---------------
display:
  - platform: nextion
    id: teplomer
    update_interval: 4s
    tft_url: http://192.168.0.16:8123/local/nextion/nextion.tft
    lambda: |-
            auto time = id(sntp_time).now();

                it.set_component_text_printf("heure","%02d",time.hour);
                it.set_component_text_printf("minute","%02d",time.minute);
                it.set_component_text_printf("date",id(date_simple).state.c_str());
                it.send_command_printf("%s.pic=%.0f", "icon",id(icon_meteo).state);
                it.send_command_printf("%s.pic=%.0f", "icon_jour",id(icon_jour_0).state);
                it.send_command_printf("%s.pic=%.0f", "icon_dem",id(icon_jour_1).state);
                it.send_command_printf("%s.pic=%.0f", "Icon_2j",id(icon_jour_2).state);
                it.send_command_printf("%s.pic=%.0f", "Icon_3j",id(icon_jour_3).state);
                it.set_component_text_printf("T_min_jour","%.0f",id(jour_tmin).state);
                it.set_component_text_printf("T_max_jour","%.0f",id(jour_tmax).state);
                it.set_component_text_printf("T_min_dem","%.0f",id(dem_tmin).state);
                it.set_component_text_printf("T_max_dem","%.0f",id(dem_tmax).state);
                it.set_component_text_printf("T_min_j2","%.0f",id(j2_tmin).state);
                it.set_component_text_printf("T_max_j2","%.0f",id(j2_tmax).state);
                it.set_component_text_printf("T_min_j3","%.0f",id(j3_tmin).state);
                it.set_component_text_printf("T_max_j3","%.0f",id(j3_tmax).state);
                it.set_component_value("temp_1",id(sonde_ext_temp).state);
                it.set_component_value("hum_1",id(sonde_humi_ext).state);
                it.send_command_printf("%s.picc=%.0f","gel",id(alerte_gel).state);
                it.send_command_printf("%s.picc=%.0f","neige",id(alerte_neige).state);
                it.set_component_value("alert_coul",id(alerte_coul).state);
                it.send_command_printf("%s.pic=%.0f","alerte_rain",id(alerte_rain).state);
                it.send_command_printf("%s.pic=%.0f", "mn_0",id(pluie_0mn).state);
                it.send_command_printf("%s.pic=%.0f", "mn_5",id(pluie_5mn).state);
                it.send_command_printf("%s.pic=%.0f", "mn_10",id(pluie_10mn).state);
                it.send_command_printf("%s.pic=%.0f", "mn_15",id(pluie_15mn).state);
                it.send_command_printf("%s.pic=%.0f", "mn_20",id(pluie_20mn).state);
                it.send_command_printf("%s.pic=%.0f", "mn_25",id(pluie_25mn).state);
                it.send_command_printf("%s.pic=%.0f", "mn_30",id(pluie_30mn).state);
                it.send_command_printf("%s.pic=%.0f", "mn_35",id(pluie_35mn).state);
                it.send_command_printf("%s.pic=%.0f", "mn_40",id(pluie_40mn).state);
                it.send_command_printf("%s.pic=%.0f", "mn_45",id(pluie_45mn).state);
                it.send_command_printf("%s.pic=%.0f", "mn_50",id(pluie_50mn).state);
                it.send_command_printf("%s.pic=%.0f", "mn_55",id(pluie_55mn).state);
                it.send_command_printf("%s.pic=%.0f", "alert_vent",id(alert_vent).state);
                it.send_command_printf("%s.pic=%.0f", "alert_inondat",id(alert_inondation).state);
                it.send_command_printf("%s.pic=%.0f", "alert_orages",id(alert_orages).state);
                it.send_command_printf("%s.pic=%.0f", "alert_pluie_in",id(alert_pluie_inondation).state);
                it.send_command_printf("%s.pic=%.0f", "alert_neig_ver",id(alert_neige_verglas).state);
                it.send_command_printf("%s.pic=%.0f", "alert_froid",id(alert_grand_froid).state);
                it.send_command_printf("%s.pic=%.0f", "alert_vagues",id(alert_vagues_submersion).state);
                it.send_command_printf("%s.pic=%.0f", "uv",id(uv_prob).state);
                it.set_component_text_printf("proc_plu","%.0f",id(pluie_proch).state);


                it.send_command_printf("%s.pic=%.0f", "icon_dem",id(icon_jour_1).state);
                it.send_command_printf("%s.pic=%.0f", "Icon_2j",id(icon_jour_2).state);
                it.send_command_printf("%s.pic=%.0f", "Icon_3j",id(icon_jour_3).state);
                it.send_command_printf("%s.pic=%.0f", "Icon_4j",id(icon_jour_4).state);
                it.send_command_printf("%s.pic=%.0f", "Icon_5j",id(icon_jour_5).state);
                it.send_command_printf("%s.pic=%.0f", "Icon_6j",id(icon_jour_6).state);
                it.send_command_printf("%s.pic=%.0f", "Icon_7j",id(icon_jour_7).state);
                it.send_command_printf("%s.pic=%.0f", "Icon_8j",id(icon_jour_8).state);
                it.set_component_text_printf("T_min_jour","%.0f",id(jour_tmin).state);
                it.set_component_text_printf("T_max_jour","%.0f",id(jour_tmax).state);
                it.set_component_text_printf("T_min_dem","%.0f",id(dem_tmin).state);
                it.set_component_text_printf("T_max_dem","%.0f",id(dem_tmax).state);
                it.set_component_text_printf("T_min_j2","%.0f",id(j2_tmin).state);
                it.set_component_text_printf("T_max_j2","%.0f",id(j2_tmax).state);
                it.set_component_text_printf("T_min_j3","%.0f",id(j3_tmin).state);
                it.set_component_text_printf("T_max_j3","%.0f",id(j3_tmax).state);
                it.set_component_text_printf("T_max_j4","%.0f",id(j4_tmax).state);
                it.set_component_text_printf("T_min_j4","%.0f",id(j4_tmin).state);
                it.set_component_text_printf("T_max_j5","%.0f",id(j5_tmax).state);
                it.set_component_text_printf("T_min_j5","%.0f",id(j5_tmin).state);
                it.set_component_text_printf("T_max_j6","%.0f",id(j6_tmax).state);
                it.set_component_text_printf("T_min_j6","%.0f",id(j6_tmin).state);
                it.set_component_text_printf("T_max_j7","%.0f",id(j7_tmax).state);
                it.set_component_text_printf("T_min_j7","%.0f",id(j7_tmin).state);
                it.set_component_text_printf("T_max_j8","%.0f",id(j8_tmax).state);
                it.set_component_text_printf("T_min_j8","%.0f",id(j8_tmin).state);

                it.send_command_printf("%s.pic=%.0f", "icon_h0",id(heure_icon_1).state);
                it.set_component_text_printf("T_h0","%.0f",id(heure_t_1).state);
                it.send_command_printf("%s.pic=%.0f", "icon_h1",id(heure_icon_2).state);
                it.set_component_text_printf("T_h1","%.0f",id(heure_t_2).state);
                it.send_command_printf("%s.pic=%.0f", "icon_h2",id(heure_icon_3).state);
                it.set_component_text_printf("T_h2","%.0f",id(heure_t_3).state);
                it.send_command_printf("%s.pic=%.0f", "icon_h3",id(heure_icon_4).state);
                it.set_component_text_printf("T_h3","%.0f",id(heure_t_4).state);
                it.send_command_printf("%s.pic=%.0f", "icon_h4",id(heure_icon_5).state);
                it.set_component_text_printf("T_h4","%.0f",id(heure_t_5).state);
                it.send_command_printf("%s.pic=%.0f", "icon_h5",id(heure_icon_6).state);
                it.set_component_text_printf("T_h5","%.0f",id(heure_t_6).state);
                it.send_command_printf("%s.pic=%.0f", "icon_h6",id(heure_icon_7).state);
                it.set_component_text_printf("T_h6","%.0f",id(heure_t_7).state);
                it.send_command_printf("%s.pic=%.0f", "icon_h7",id(heure_icon_8).state);
                it.set_component_text_printf("T_h7","%.0f",id(heure_t_8).state);